using Frame3ddn.Model;
using Frame3ddn.Parsers;
using Frame3ddn.Writers;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Xunit;

namespace Frame3ddn.Test
{

    public class SolverTest
    {
        // ───────────────────────────── upstream frame3dd examples ─────────────────────────────
        // Same 10 fixtures parsed three ways (.csv, .3dd) and compared against the corresponding
        // reference output (_out.CSV vs .out). The historical 2018 NT-derivative fixtures live
        // in their own directory and are exercised by TestCases2018.

        [Theory]
        [InlineData("exA")]
        [InlineData("exB")]
        [InlineData("exC")]
        [InlineData("exD")]
        [InlineData("exE")]
        [InlineData("exF")]
        [InlineData("exG")]
        [InlineData("exH")]
        [InlineData("exI")]
        [InlineData("exJ")]
        public void Frame3ddExamplesCsv(string fileName)
        {
            using StreamReader sr = new StreamReader(GetFrame3ddExamplePath(fileName + ".csv"));
            Input input = CsvInputParser.Parse(sr);
            List<LoadCaseOutput> reference = CsvOutputParser.Parse(
                File.ReadAllText(GetFrame3ddExamplePath(fileName + "_out.CSV")));

            // _out.CSV emits a row per node for both the displacement and reaction tables,
            // including all-zero rows — drop those zero rows on both sides before comparing.
            CompareSolveAgainstReference(input, reference, fileName, ignoreZeroRows: true);
        }

        [Theory]
        [InlineData("exA")]
        [InlineData("exB")]
        [InlineData("exC")]
        [InlineData("exD")]
        [InlineData("exE")]
        [InlineData("exF")]
        [InlineData("exG")]
        [InlineData("exH")]
        [InlineData("exI")]
        [InlineData("exJ")]
        public void Frame3ddExamples3dd(string fileName)
        {
            using StreamReader sr = new StreamReader(GetFrame3ddExamplePath(fileName + ".3dd"));
            Input input = ThreeDdInputParser.Parse(sr);
            string outText = File.ReadAllText(GetFrame3ddExamplePath(fileName + ".out"));
            List<LoadCaseOutput> reference = OutOutputParser.Parse(outText);
            // Pull modal results from the same .out so frequencies are cross-validated alongside
            // the static sections. Empty list for fixtures without modal analysis (exA), and
            // skipped for exD/exJ — these are unrestrained structures with rigid-body modes
            // near 0 Hz where Subspace's seeding lands on slightly different near-zero
            // eigenvalues than upstream's (see Frame3ddExamples_LowestModeMatchesUpstream).
            bool isRigidBody = fileName == "exD" || fileName == "exJ";
            List<ModalResult> referenceModal = isRigidBody
                ? null
                : OutOutputParser.ParseModalResults(outText);

            CompareSolveAgainstReference(input, reference, fileName + ".3dd",
                referenceModal: referenceModal != null && referenceModal.Count > 0 ? referenceModal : null);
        }

        [Theory]
        [InlineData("B")]
        [InlineData("NTB")]
        [InlineData("NTE")]
        [InlineData("NTF")]
        [InlineData("NTG")]
        [InlineData("NTI")]
        public void TestCases2018(string fileName)
        {
            // NT-prefixed derivatives of the upstream exB/exE/exF/exG/exI examples (geometric
            // stiffness off, dynamic-analysis section trimmed, sometimes fewer load cases),
            // plus B (modified exC). The .out references were generated by the C frame3dd
            // binary on those modified inputs and may carry more load cases than the (trimmed)
            // input now produces — clip to what we ran.
            using StreamReader sr = new StreamReader(GetTestCases2018Path(fileName + ".csv"));
            Input input = CsvInputParser.Parse(sr);
            string outText = File.ReadAllText(GetTestCases2018Path(fileName + ".out"));
            List<LoadCaseOutput> reference = OutOutputParser.Parse(outText);
            List<ModalResult> referenceModal = OutOutputParser.ParseModalResults(outText);

            CompareSolveAgainstReference(input, reference, fileName + ".2018",
                clipReference: true,
                referenceModal: referenceModal.Count > 0 ? referenceModal : null);
        }



        // ─────────────────────────────────── shared helpers ───────────────────────────────────

        /// <summary>
        /// Solves <paramref name="input"/>, asserts the result matches <paramref name="reference"/>,
        /// and (if a debugger is attached) drops a side-by-side .expected.out / .actual.out pair
        /// into the per-run snapshot directory.
        /// </summary>
        /// <param name="snapshotName">
        ///   Base name (no extension) for the debug snapshot files. Variants disambiguate by
        ///   suffix — e.g. <c>exA</c>, <c>exA.3dd</c>, <c>B.2018</c>.
        /// </param>
        /// <param name="ignoreZeroRows">
        ///   Drop all-zero displacement and reaction rows on both sides before comparing.
        ///   Needed when the reference (e.g. <c>_out.CSV</c>) emits a row per node and the
        ///   solver only emits non-trivial rows.
        /// </param>
        /// <param name="clipReference">
        ///   Trim the reference to <c>outputCalculated.LoadCaseOutputs.Count</c> load cases
        ///   first. Used by the historical 2018 fixtures whose <c>.out</c> files were generated
        ///   from richer inputs than the trimmed test fixture.
        /// </param>
        private static void CompareSolveAgainstReference(
            Input input,
            List<LoadCaseOutput> reference,
            string snapshotName,
            bool ignoreZeroRows = false,
            bool clipReference = false,
            IReadOnlyList<ModalResult> referenceModal = null)
        {
            Output outputCalculated = new Solver().Solve(input);

            if (clipReference)
                reference = reference.Take(outputCalculated.LoadCaseOutputs.Count).ToList();

            if (DebugSnapshot.Enabled)
                WriteDebugSnapshot(snapshotName, reference, outputCalculated);

            // The frame3dd output files are inconsistent w.r.t. the PEAK section — exA/exD/
            // exH/exJ omit it in .out, others include it; _out.CSV always has it. Skip the
            // section only when the reference itself doesn't supply it.
            bool referenceHasPeak = reference.Any(lc => lc.PeakFrameElementInternalForces.Count > 0);
            Output expectedOutput = new Output("", reference, referenceModal);
            OutputAsserts.OutputAssertEqual(expectedOutput, outputCalculated,
                new OutputAssertOptions
                {
                    IgnorePeakForces = !referenceHasPeak,
                    IgnoreZeroRows = ignoreZeroRows,
                    IgnoreModal = referenceModal == null,
                });
        }

        private static void WriteDebugSnapshot(
            string snapshotName,
            List<LoadCaseOutput> reference,
            Output outputCalculated)
        {
            string classDir = DebugSnapshot.GetClassDir(nameof(SolverTest));
            // The solver's TextOutput is `OutWriter.InputDataToString + OutWriter.OutputDataToString`.
            // Slice off the OutputDataToString suffix to recover the shared input preamble so
            // both files start with it and the diff is purely the load-case section.
            string actualOutSection = OutWriter.OutputDataToString(outputCalculated.LoadCaseOutputs.ToList());
            int outputStart = outputCalculated.TextOutput.IndexOf(actualOutSection, StringComparison.Ordinal);
            string preamble = outputStart >= 0 ? outputCalculated.TextOutput.Substring(0, outputStart) : "";
            DebugSnapshot.WriteText(classDir, snapshotName + ".expected.out",
                preamble + OutWriter.OutputDataToString(reference));
            DebugSnapshot.WriteText(classDir, snapshotName + ".actual.out",
                preamble + actualOutSection);
        }

        // ──────────────────────────────── path-resolution helpers ─────────────────────────────

        private static string GetFrame3ddExamplePath(string fileName) =>
            Path.Combine(GetTestDataDir(), "frame3dd-examples", fileName);

        private static string GetTestCases2018Path(string fileName) =>
            Path.Combine(GetTestDataDir(), "testcases-2018", fileName);

        private static string GetTestDataDir()
        {
            // cwd at runtime is bin/Debug/net9.0; walk up three levels to the test project root.
            string projectDir = Directory.GetParent(Directory.GetParent(Directory.GetParent(
                Directory.GetCurrentDirectory().ToString()).ToString()).ToString()).ToString();
            return Directory.GetDirectories(projectDir, "TestData")[0];
        }
    }
}
